/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjadwalan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ehazard
 */
public class datawaktu extends javax.swing.JInternalFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form datawaktu
     */
    public datawaktu() throws SQLException {
        initComponents();
        koneksi ObjKoneksi = new koneksi();
        con = ObjKoneksi.bukaKoneksi();
        stat = con.createStatement();
        //UpdateTabel();
        tampil_database();
        jTextField1.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jComboBox5 = new javax.swing.JComboBox<String>();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Waktu");
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(900, 500));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Waktu", "Hari", "Waktu Mulai", "Waktu Selesai"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1.setText("Id Waktu");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Hari");

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Waktu Selesai");

        jTextField1.setText("Auto");

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Waktu Mulai");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Waktu Mulai--", "07.00", "07.45", "08.30", "09.15", "09.30", "10.15", "11.00", "11.45", "12.10", "12.55", "13.40", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Waktu Selesai--", "07.45", "08.30", "09.15", "09.30", "10.15", "11.00", "11.45", "12.10", "12.55", "13.40", "14.25" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Hari--", "SENIN", "SELASA", "RABU", "KAMIS", "JUMAT", "SABTU" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 343, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
   DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
   //jTextField1.enable(false);
   jTextField1.setText(dtm.getValueAt(i,0).toString());
   jComboBox5.setSelectedItem(dtm.getValueAt(i, 1));
   jComboBox1.setSelectedItem(dtm.getValueAt(i, 2));
   jComboBox2.setSelectedItem(dtm.getValueAt(i, 3));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            hapus();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField4KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

     //menampilkan isi database ke jtabel
    public void tampil_database(){
        //UpdateTabel();
        try {
            sql = "SELECT * FROM waktu;";
            rs = stat.executeQuery(sql);
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        String [] data = new String[7];
        int i = 1;
       
        while(rs.next()) {
            data[0] = rs.getString("idwaktu");
            data[1] = rs.getString("hari");
            data[2] = rs.getString("waktu_mulai");
            data[3] = rs.getString("waktu_selesai");
            dtm.addRow(data);
            i++;
            
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void hapus(){
        String id = "";
            try {
                id = jTextField1.getText();
                String sql = "DELETE from waktu where idwaktu='"+id+"'";
                //String sql = "insert into waktu values('"+id+"','"+nama+"','"+waktu1+"','"+waktu2+"')";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data BERHASIL terhapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                kosong();
                tampil_database();
                
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                 JOptionPane.showMessageDialog(null, e);
           }
    }
    public void kosong(){
        //jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        //jTextField5.setText("");
        jTextField1.setText("Auto");
    }    
private void save(){
     if(jComboBox1.getSelectedItem().equals("--Pilih waktu mulai--")){
            JOptionPane.showMessageDialog(null,"Maaf, waktu mulai belum di isi!");
            jComboBox1.requestFocus();
        }
        else if(jComboBox2.getSelectedItem().equals("--Pilih Waktu selesai--")){
            JOptionPane.showMessageDialog(null,"Maaf, waktu selesai belum di isi!");
            jComboBox2.requestFocus();
        }
        else if(jTextField1.getText().trim().equals("Auto")){
            String id = "", nama1 = "",nama2="",waktu1="",waktu2="",waktu3="",waktu4="";
            int mulai1,selesai1,mulai2,selesai2,hari1,hari2;
            try {
                id = jTextField1.getText();
                hari1 = jComboBox5.getSelectedIndex();
                //hari 1
                if(hari1==0){nama1="--Pilih Hari--";}
                if(hari1==1){nama1="SENIN";}
                if(hari1==2){nama1="SELASA";}
                if(hari1==3){nama1="RABU";}
                if(hari1==4){nama1="KAMIS";}
                if(hari1==5){nama1="JUMAT";}
                if(hari1==6){nama1="SABTU";}
                mulai1 = jComboBox1.getSelectedIndex();
                selesai1 = jComboBox2.getSelectedIndex();
                //pertama
                if(mulai1==0){waktu1="--Pilih Waktu Mulai--";}
                if(mulai1==1){waktu1="07.00";}
                if(mulai1==2){waktu1="07.45";}
                if(mulai1==3){waktu1="08.30";}
                if(mulai1==4){waktu1="09.15";}
                if(mulai1==5){waktu1="09.30";}
                if(mulai1==6){waktu1="10.15";}
                if(mulai1==7){waktu1="11.00";}
                if(mulai1==8){waktu1="11.45";}
                if(mulai1==9){waktu1="12.10";}
                if(mulai1==10){waktu1="12.55";}
                if(mulai1==11){waktu1="13.45";}
                if(selesai1==0){waktu2="--Pilih waktu selesai--";}
                if(selesai1==1){waktu2="07.45";}
                if(selesai1==2){waktu2="08.30";}
                if(selesai1==3){waktu2="09.15";}
                if(selesai1==4){waktu2="09.30";}
                if(selesai1==5){waktu2="10.15";}
                if(selesai1==6){waktu2="11.00";}
                if(selesai1==7){waktu2="11.45";}
                if(selesai1==8){waktu2="12.10";}
                if(selesai1==9){waktu2="12.55";}
                if(selesai1==10){waktu2="13.40";}
                if(selesai1==11){waktu2="14.25";}
                String sql = "INSERT INTO `waktu` (`idwaktu`, `hari1`, `waktu_mulai1`, `waktu_selesai1`) VALUES (NULL, '"+nama1+"', '"+waktu1+"', '"+waktu2+"');";
                //String sql = "insert into waktu values('"+id+"','"+nama+"','"+waktu1+"','"+waktu2+"')";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data BERHASIL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                kosong();
                tampil_database();
                
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                 JOptionPane.showMessageDialog(null, e);
            }
        }else if(!jTextField1.getText().trim().equals("Auto")){
            String id = "", nama1 = "",nama2="",waktu1="",waktu2="",waktu3="",waktu4="";
            int mulai1,selesai1,mulai2,selesai2,hari1,hari2 ;
            try {
                id = jTextField1.getText();
                hari1 = jComboBox5.getSelectedIndex();
                //hari 1
                if(hari1==0){nama1="--Pilih Hari--";}
                if(hari1==1){nama1="SENIN";}
                if(hari1==2){nama1="SELASA";}
                if(hari1==3){nama1="RABU";}
                if(hari1==4){nama1="KAMIS";}
                if(hari1==5){nama1="JUMAT";}
                if(hari1==6){nama1="SABTU";}
                mulai1 = jComboBox1.getSelectedIndex();
                selesai1 = jComboBox2.getSelectedIndex();
                //pertama
                if(mulai1==0){waktu1="--Pilih Waktu Mulai--";}
                if(mulai1==1){waktu1="07.00";}
                if(mulai1==2){waktu1="07.45";}
                if(mulai1==3){waktu1="08.30";}
                if(mulai1==4){waktu1="09.15";}
                if(mulai1==5){waktu1="09.30";}
                if(mulai1==6){waktu1="10.15";}
                if(mulai1==7){waktu1="11.00";}
                if(mulai1==8){waktu1="11.45";}
                if(mulai1==9){waktu1="12.10";}
                if(mulai1==10){waktu1="12.55";}
                if(mulai1==11){waktu1="13.45";}
                if(selesai1==0){waktu2="--Pilih waktu selesai--";}
                if(selesai1==1){waktu2="07.45";}
                if(selesai1==2){waktu2="08.30";}
                if(selesai1==3){waktu2="09.15";}
                if(selesai1==4){waktu2="09.30";}
                if(selesai1==5){waktu2="10.15";}
                if(selesai1==6){waktu2="11.00";}
                if(selesai1==7){waktu2="11.45";}
                if(selesai1==8){waktu2="12.10";}
                if(selesai1==9){waktu2="12.55";}
                if(selesai1==10){waktu2="13.40";}
                if(selesai1==11){waktu2="14.25";}
                String sql = "Update waktu set idwaktu='"+id+"',hari1='"+nama1+"',waktu_mulai1='"+waktu1+"',waktu_selesai1='"+waktu2+"' where idwaktu='"+id+"'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data BERHASIL terubah" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                kosong();
                tampil_database();
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, e);
                //JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
}
}

